apiVersion: v1
kind: Service
metadata:
  name: mission-service
  namespace: fleet-dev
spec:
  selector:
    app: mission-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP