apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: fleet-dev
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: fleet-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false  
      containers:
      - name: kafka
        image: confluentinc/confluent-local:7.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kafka.fleet-dev.svc.cluster.local:9092"
