server:
  port: 8080 

app:
  security:
    enabled: false

spring:
  application:
    name: vehicle-service
  kafka:
    bootstrap-servers: localhost:9092
  

  datasource:
  
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vehicles_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
