server:
  port: 8080 

app:
  security:
    enabled: ${APP_SECURITY_ENABLED:true}
    keycloak:
      realm-url: ${KEYCLOAK_REALM_URL:http://keycloak:8080/realms/flotte-management}
      client-id: ${KEYCLOAK_CLIENT_ID:flotte-services}
      verify-issuer: ${KEYCLOAK_VERIFY_ISSUER:false}
      jwt-public-key: ${JWT_PUBLIC_KEY:}

spring:
  application:
    name: vehicle-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
  

  datasource:
  
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vehicles_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.security.keycloak.realm-url}/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
