apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: fleet-dev
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP

