apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-service
  namespace: fleet-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-service
  template:
    metadata:
      labels:
        app: vehicle-service
    spec:
      containers:
        - name: vehicle-service
          image: vehicle-service:latest
          imagePullPolicy: Never        # image locale Minikube
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-postgresql:5432/vehicles_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"